import Head from "next/head";

//Components
import VideoBackground from "../components/VideoBackground";
import EnterBtn from "../components/EnterBtn";

export default function Home({ video }) {
  return (
    <div>
      <Head>
        <title>Patrick Clichy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fixed z-20 w-screen h-screen flex items-center justify-center flex-col text-center">
        <div className="header flex-1 flex flex-col items-center justify-center">
          <h1 className="text-4xl mb-5 font-medium text-white sm:text-5xl">
            Patrick Clichy
          </h1>
          <h3 className="text-1xl font-extralight text-white mt-4 sm:text-1xl">
            Artiste peintre
          </h3>
        </div>
        <EnterBtn />
      </main>
      <VideoBackground videoURL={video.video_files[1].link} className="fixed" />
    </div>
  );
}

export async function getStaticProps(context) {
  const res = await fetch(`https://api.pexels.com/videos/videos/1970093`, {
    headers: {
      Authorization: process.env.PEXEL_API_KEY,
    },
  });

  const video = await res.json();
  console.log(video);

  return {
    props: { video },
  };
}
